### ISSUE TITLE
为什么它会表示找不到paperId呢//杭电我爱记单词

### ISSUE THREAD

**Issue by ztr2006** [l1nkccc/WoBuAiJiDanCi#1]
Traceback (most recent call last):
  File "C:\Users\LL\Desktop\main.py", line 271, in <module>
    main()
    ~~~~^^
  File "C:\Users\LL\Desktop\main.py", line 267, in main
    exam(token, 1, mode, delay)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LL\Desktop\main.py", line 110, in exam
    ans = getAnswer(paper)
  File "C:\Users\LL\Desktop\main.py", line 130, in getAnswer
    "paperId": paper["paperId"],
               ~~~~~^^^^^^^^^^^
KeyError: 'paperId'

C:\Users\LL\Desktop>
@kn1l

**Comment by kn1l** [comment]
请问自测正常吗，我这里尝试了自测和考试都没有出现这个报错@ztr2006

**Comment by ztr2006** [comment]
有没有可能是测试的单词的问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月1日(周日) 晚上9:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kn1l/WoBuAiJiDanCi] 为什么它会表示找不到paperId呢//杭电我爱记单词 (Issue #1)




 
***@***.***

**Comment by ztr2006** [comment]
嗯，，，是这样的，我第一次自测正常运行，但是第二次自测又报错了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月1日(周日) 晚上9:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kn1l/WoBuAiJiDanCi] 为什么它会表示找不到paperId呢//杭电我爱记单词 (Issue #1)




 
***@***.***

**Comment by ztr2006** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月1日(周日) 晚上9:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kn1l/WoBuAiJiDanCi] 为什么它会表示找不到paperId呢//杭电我爱记单词 (Issue #1)




 
***@***.***

**Comment by kn1l** [comment]
你加一下我qq964362205

**Comment by kn1l** [comment]
短时间内多次测试导致的
